[project]
name = "cs2-chroma"
license = "MIT"
version = "0.2.0"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.5",
    "websocket-client>=1.9.2",
    "winrt-windows-foundation>=3.2.1",
    "winrt-windows-media-control>=3.2.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pyinstaller>=6.22.3",
]

[tool.ruff.lint]
extend-select = [
    "B",
    "C4",
    "E",
    "F",
    "FBT",
    "I",
    "ICN",
    "ISC",
    "PTH",
    "PYI",
    "RET",
    "RUF",
    "S",
    "SIM",
    "SIM",
    "TID",
    "UP",
    "W"
]
ignore = [
    "E501"
]

[tool.pyrefly]
preset = "basic"
project-includes = [
    "**/*.py*",
]
